<?php

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\AreaCarServiceProvider::class,
    App\Providers\BodyTypeInfoServiceProvider::class,
    App\Providers\CarServiceProvider::class,
    App\Providers\DisplacementListServiceProvider::class,
    App\Providers\FeaturedBodyTypeListServiceProvider::class,
    App\Providers\FeaturedBrandListServiceProvider::class,
    App\Providers\Filament\AdminPanelProvider::class,
    App\Providers\ManufacturerListServiceProvider::class,
    App\Providers\MileageListServiceProvider::class,
    App\Providers\PriceListServiceProvider::class,
    App\Providers\RegionServiceProvider::class,
    App\Providers\RidingCapacityListServiceProvider::class,
    App\Providers\SelectAreaCarServiceProvider::class,
    App\Providers\SelectBodyTypeListServiceProvider::class,
    App\Providers\SelectCarDataServiceProvider::class,
    App\Providers\SelectManufacturerListServiceProvider::class,
    App\Providers\RoomServiceProvider::class,
    App\Providers\MessageServiceProvider::class,
    App\Providers\PasswordServiceProvider::class,
    App\Providers\MemberServiceProvider::class,
];
