<?php

namespace Database\Seeders\Mst;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MstManuFacturersSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::connection('mst')->table('mst_manufacturers')->insert([
            // 国産車（JP）
            ['name' => 'LEXUS',           'name_kana' => 'レクサス',             'display_name' => 'レクサス',         'code' => 'LEXUS01',          'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 100,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'TOYOTA',          'name_kana' => 'トヨタ',               'display_name' => 'トヨタ',           'code' => 'TOYOTA01',         'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 110,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'HONDA',           'name_kana' => 'ホンダ',               'display_name' => 'ホンダ',           'code' => 'HONDA01',          'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 120,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'NISSAN',          'name_kana' => '日産',                 'display_name' => 'ニッサン',         'code' => 'NISSAN01',         'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 130,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'SUZUKI',          'name_kana' => 'スズキ',               'display_name' => 'スズキ',           'code' => 'SUZUKI01',         'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 140,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'DAIHATSU',        'name_kana' => 'ダイハツ',             'display_name' => 'ダイハツ',         'code' => 'DAIHATSU01',       'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 150,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'MAZDA',           'name_kana' => 'マツダ',               'display_name' => 'マツダ',           'code' => 'MAZDA01',          'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 160,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'SUBARU',          'name_kana' => 'スバル',               'display_name' => 'スバル',           'code' => 'SUBARU01',         'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 170,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'MITSUBISHI',      'name_kana' => 'ミツビシ',             'display_name' => '三菱',             'code' => 'MITSUBISHI01',     'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 180,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'ISUZU',           'name_kana' => 'イスヾ',               'display_name' => 'いすゞ',           'code' => 'ISUZU01',          'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 190,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'MITSUOKA',        'name_kana' => 'ミツオカ',             'display_name' => '光岡自動車',       'code' => 'MITSUOKA01',       'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 200,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'TOMMYKAIRA',      'name_kana' => 'トミーカイラ',         'display_name' => 'トミーカイラ',     'code' => 'TOMMYKAIRA01',     'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 210,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'HINO',            'name_kana' => 'ヒノ',                 'display_name' => '日野自動車',       'code' => 'HINO01',           'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 220,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'UDTrucks',        'name_kana' => 'ユーディートラックス', 'display_name' => 'UDトラックス',     'code' => 'UDTRUCKS01',       'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 230,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'MitsubishiFuso',  'name_kana' => 'ミツビシフソウ',       'display_name' => '三菱ふそう',       'code' => 'MITSUBISHIFUSO01', 'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 240,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'etc',             'name_kana' => 'その他',               'display_name' => '国産車その他',     'code' => 'ETC01',            'url' => null, 'description' => null, 'country_code' => 'JP', 'sort_order' => 999,  'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],

            // ドイツ車（DE）1000番台
            ['name' => 'Mercedes-Benz',   'name_kana' => 'メルセデス・ベンツ',   'display_name' => 'メルセデス・ベンツ', 'code' => 'MBENZ01',        'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1000, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Mercedes-AMG',    'name_kana' => 'メルセデスアムジー',   'display_name' => 'メルセデスAMG',    'code' => 'MBAMG01',          'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1010, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Mercedes-Maybach','name_kana' => 'メルセデス・マイバッハ','display_name' => 'マイバッハ',      'code' => 'MBMAYBACH01',      'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1020, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'AMG',             'name_kana' => 'アムジー',             'display_name' => 'AMG',              'code' => 'AMG01',            'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1030, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Maybach',         'name_kana' => 'マイバッハ',           'display_name' => 'マイバッハ',       'code' => 'MAYBACH01',        'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1040, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Smart',           'name_kana' => 'スマート',             'display_name' => 'スマート',         'code' => 'SMART01',          'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1050, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'BMW',             'name_kana' => 'ビーエムダブリュー',   'display_name' => 'BMW',              'code' => 'BMW01',            'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1060, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'BMWAlpina',       'name_kana' => 'ビーエムダブリューアルピナ','display_name' => 'BMWアルピナ', 'code' => 'BMWALPINA01',      'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1070, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Audi',            'name_kana' => 'アウディ',             'display_name' => 'アウディ',         'code' => 'AUDI01',           'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1080, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Volkswagen',      'name_kana' => 'フォルクスワーゲン',   'display_name' => 'VW',               'code' => 'VW01',             'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1090, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Opel',            'name_kana' => 'オペル',               'display_name' => 'オペル',           'code' => 'OPEL01',           'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1100, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Porsche',         'name_kana' => 'ポルシェ',             'display_name' => 'ポルシェ',         'code' => 'PORSCHE01',        'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1110, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Brabus',          'name_kana' => 'ブラバス',             'display_name' => 'ブラバス',         'code' => 'BRABUS01',         'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1120, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Yes',             'name_kana' => 'イエス',               'display_name' => 'イエス',           'code' => 'YES01',            'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1130, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Artega',          'name_kana' => 'アルテガ',             'display_name' => 'アルテガ',         'code' => 'ARTEGA01',         'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1140, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Mini',            'name_kana' => 'ミニ',                 'display_name' => 'MINI',             'code' => 'MINI01',           'url' => null, 'description' => null, 'country_code' => 'DE', 'sort_order' => 1150, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],

            // アメリカ車（US）2000番台
            ['name' => 'Cadillac',        'name_kana' => 'キャデラック',         'display_name' => 'キャデラック',     'code' => 'CADILLAC01',       'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2000, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Chevrolet',       'name_kana' => 'シボレー',             'display_name' => 'シボレー',         'code' => 'CHEVROLET01',      'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2010, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Buick',           'name_kana' => 'ビュイック',           'display_name' => 'ビュイック',       'code' => 'BUICK01',          'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2020, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Pontiac',         'name_kana' => 'ポンテアック',         'display_name' => 'ポンテアック',     'code' => 'PONTIAC01',        'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2030, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Saturn',          'name_kana' => 'サターン',             'display_name' => 'サターン',         'code' => 'SATURN01',         'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2040, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Hummer',          'name_kana' => 'ハマー',               'display_name' => 'ハマー',           'code' => 'HAMMER01',         'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2050, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'GMC',             'name_kana' => 'ジーエムシー',         'display_name' => 'GMC',              'code' => 'GMC01',            'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2060, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Ford',            'name_kana' => 'フォード',             'display_name' => 'フォード',         'code' => 'FORD01',           'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2070, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Lincoln',         'name_kana' => 'リンカーン',           'display_name' => 'リンカーン',       'code' => 'LINCOLN01',        'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2080, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Mercury',         'name_kana' => 'マーキュリー',         'display_name' => 'マーキュリー',     'code' => 'MERCURY01',        'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2090, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Chrysler',        'name_kana' => 'クライスラー',         'display_name' => 'クライスラー',     'code' => 'CHRYSLER01',       'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2100, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Dodge',           'name_kana' => 'ダッジ',               'display_name' => 'ダッジ',           'code' => 'DODGE01',          'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2110, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Plymouth',        'name_kana' => 'プリムス',             'display_name' => 'プリムス',         'code' => 'PLYMOUTH01',       'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2120, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'AMC',             'name_kana' => 'エーエムシー',         'display_name' => 'AMC',              'code' => 'AMC01',            'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2130, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'AMCJeep',         'name_kana' => 'AMCジープ',            'display_name' => 'AMCジープ',        'code' => 'AMCJEEP01',        'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2140, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Jeep',            'name_kana' => 'ジープ',               'display_name' => 'ジープ',           'code' => 'JEEP01',           'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2150, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Oldsmobile',      'name_kana' => 'オールズモビル',       'display_name' => 'オールズモビル',   'code' => 'OLDS01',           'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2160, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Winnebago',       'name_kana' => 'ウィネベーゴ',         'display_name' => 'ウィネベーゴ',     'code' => 'WINNEBAGO01',      'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2170, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'DMC',             'name_kana' => 'ディーエムシー',       'display_name' => 'DMC',              'code' => 'DMC01',            'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2180, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Tesla',           'name_kana' => 'テスラ',               'display_name' => 'テスラ',           'code' => 'TESLA01',          'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2190, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'USLexus',         'name_kana' => '米国レクサス',         'display_name' => 'レクサス（米国）', 'code' => 'USLEXUS01',        'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2200, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'USInfiniti',      'name_kana' => '米国インフィニティ',   'display_name' => 'インフィニティ（米国）','code' => 'USINFINITI01', 'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2210, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'USAcura',         'name_kana' => '米国アキュラ',         'display_name' => 'アキュラ（米国）', 'code' => 'USACURA01',        'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2220, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'USToyota',        'name_kana' => '米国トヨタ',           'display_name' => 'トヨタ（米国）',   'code' => 'USTOYOTA01',       'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2230, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'USScion',         'name_kana' => '米国サイオン',         'display_name' => 'サイオン（米国）', 'code' => 'USSCION01',        'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2240, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'USNissan',        'name_kana' => '米国日産',             'display_name' => '日産（米国）',     'code' => 'USNISSAN01',       'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2250, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'USHonda',         'name_kana' => '米国ホンダ',           'display_name' => 'ホンダ（米国）',   'code' => 'USHONDA01',        'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2260, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'USMazda',         'name_kana' => '米国マツダ',           'display_name' => 'マツダ（米国）',   'code' => 'USMAZDA01',        'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2270, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'USSubaru',        'name_kana' => '米国スバル',           'display_name' => 'スバル（米国）',   'code' => 'USSUBARU01',       'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2280, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'USSuzuki',        'name_kana' => '米国スズキ',           'display_name' => 'スズキ（米国）',   'code' => 'USSUZUKI01',       'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2290, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'USMitsubishi',    'name_kana' => '米国三菱',             'display_name' => '三菱（米国）',     'code' => 'USMITSUBISHI01',   'url' => null, 'description' => null, 'country_code' => 'US', 'sort_order' => 2300, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],

            // カナダ（CA）3000番台
            ['name' => 'CanadaHonda',     'name_kana' => 'カナダホンダ',         'display_name' => 'カナダホンダ',     'code' => 'CANADAHONDA01',    'url' => null, 'description' => null, 'country_code' => 'CA', 'sort_order' => 3000, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],

            // イギリス車（GB）4000番台
            ['name' => 'Rolls-Royce',     'name_kana' => 'ロールスロイス',       'display_name' => 'ロールスロイス',   'code' => 'ROLLS01',          'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4000, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Bentley',         'name_kana' => 'ベントレー',           'display_name' => 'ベントレー',       'code' => 'BENTLEY01',        'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4010, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Jaguar',          'name_kana' => 'ジャガー',             'display_name' => 'ジャガー',         'code' => 'JAGUAR01',         'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4020, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Daimler',         'name_kana' => 'デイムラー',           'display_name' => 'デイムラー',       'code' => 'DAIMLER01',        'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4030, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'LandRover',       'name_kana' => 'ランドローバー',       'display_name' => 'ランドローバー',   'code' => 'LANDROVER01',      'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4040, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'AstonMartin',     'name_kana' => 'アストンマーティン',   'display_name' => 'アストンマーティン','code' => 'ASTON01',          'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4050, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Lotus',           'name_kana' => 'ロータス',             'display_name' => 'ロータス',         'code' => 'LOTUS01',          'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4060, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'LondonTaxi',      'name_kana' => 'ロンドンタクシー',     'display_name' => 'ロンドンタクシー', 'code' => 'LONTAXI01',        'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4070, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'McLaren',         'name_kana' => 'マクラーレン',         'display_name' => 'マクラーレン',     'code' => 'MCLAREN01',        'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4080, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'MG',              'name_kana' => 'エムジー',             'display_name' => 'MG',               'code' => 'MG01',             'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4090, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Rover',           'name_kana' => 'ローバー',             'display_name' => 'ローバー',         'code' => 'ROVER01',          'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4100, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Austin',          'name_kana' => 'オースチン',           'display_name' => 'オースチン',       'code' => 'AUSTIN01',         'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4110, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Morris',          'name_kana' => 'モーリス',             'display_name' => 'モーリス',         'code' => 'MORRIS01',         'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4120, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'BL',              'name_kana' => 'ビーエル',             'display_name' => 'BL',               'code' => 'BL01',             'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4130, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Moke',            'name_kana' => 'モーク',               'display_name' => 'モーク',           'code' => 'MOKE01',           'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4140, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Marcos',          'name_kana' => 'マーコス',             'display_name' => 'マーコス',         'code' => 'MARCOS01',         'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4150, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'VandenPlas',      'name_kana' => 'バンデンプラ',         'display_name' => 'バンデンプラ',     'code' => 'VANDEN01',         'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4160, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Woolsey',         'name_kana' => 'ウーズレイ',           'display_name' => 'ウーズレイ',       'code' => 'WOOLSEY01',        'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4170, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Riley',           'name_kana' => 'ライレー',             'display_name' => 'ライレー',         'code' => 'RILEY01',          'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4180, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Caterham',        'name_kana' => 'ケータハム',           'display_name' => 'ケータハム',       'code' => 'CATERHAM01',       'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4190, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Westfield',       'name_kana' => 'ウエストフィールド',   'display_name' => 'ウエストフィールド','code' => 'WESTFIELD01',      'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4200, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Morgan',          'name_kana' => 'モーガン',             'display_name' => 'モーガン',         'code' => 'MORGAN01',         'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4210, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Panther',         'name_kana' => 'パンサー',             'display_name' => 'パンサー',         'code' => 'PANTHER01',        'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4220, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Triumph',         'name_kana' => 'トライアンフ',         'display_name' => 'トライアンフ',     'code' => 'TRIUMPH01',        'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4230, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Healey',          'name_kana' => 'ヒーレー',             'display_name' => 'ヒーレー',         'code' => 'HEALEY01',         'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4240, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Ginetta',         'name_kana' => 'ジネッタ',             'display_name' => 'ジネッタ',         'code' => 'GINETTA01',        'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4250, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Vauxhall',        'name_kana' => 'ボクスホール',         'display_name' => 'ボクスホール',     'code' => 'VAUXHALL01',       'url' => null, 'description' => null, 'country_code' => 'GB', 'sort_order' => 4260, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],

            // スウェーデン（SE）5000番台
            ['name' => 'Volvo',           'name_kana' => 'ボルボ',               'display_name' => 'ボルボ',           'code' => 'VOLVO01',          'url' => null, 'description' => null, 'country_code' => 'SE', 'sort_order' => 5000, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Saab',            'name_kana' => 'サーブ',               'display_name' => 'サーブ',           'code' => 'SAAB01',           'url' => null, 'description' => null, 'country_code' => 'SE', 'sort_order' => 5010, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Koenigsegg',      'name_kana' => 'ケーニッグゼグ',       'display_name' => 'ケーニッグゼグ',   'code' => 'KOENIGSEGG01',     'url' => null, 'description' => null, 'country_code' => 'SE', 'sort_order' => 5020, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Scania',          'name_kana' => 'スカニア',             'display_name' => 'スカニア',         'code' => 'SCANIA01',         'url' => null, 'description' => null, 'country_code' => 'SE', 'sort_order' => 5030, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],

            // フランス（FR）6000番台
            ['name' => 'Peugeot',         'name_kana' => 'プジョー',             'display_name' => 'プジョー',         'code' => 'PEUGEOT01',        'url' => null, 'description' => null, 'country_code' => 'FR', 'sort_order' => 6000, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Renault',         'name_kana' => 'ルノー',               'display_name' => 'ルノー',           'code' => 'RENAULT01',        'url' => null, 'description' => null, 'country_code' => 'FR', 'sort_order' => 6010, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Citroen',         'name_kana' => 'シトロエン',           'display_name' => 'シトロエン',       'code' => 'CITROEN01',        'url' => null, 'description' => null, 'country_code' => 'FR', 'sort_order' => 6020, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'DSAutomobiles',   'name_kana' => 'ディーエスオートモビル','display_name' => 'DSオートモビル',  'code' => 'DS01',             'url' => null, 'description' => null, 'country_code' => 'FR', 'sort_order' => 6030, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'MVS',             'name_kana' => 'エムブイエス',         'display_name' => 'MVS',              'code' => 'MVS01',            'url' => null, 'description' => null, 'country_code' => 'FR', 'sort_order' => 6040, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Bugatti',         'name_kana' => 'ブガッティ',           'display_name' => 'ブガッティ',       'code' => 'BUGATTI01',        'url' => null, 'description' => null, 'country_code' => 'FR', 'sort_order' => 6050, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Alpine',          'name_kana' => 'アルピーヌ',           'display_name' => 'アルピーヌ',       'code' => 'ALPINE01',         'url' => null, 'description' => null, 'country_code' => 'FR', 'sort_order' => 6060, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],

            // イタリア（IT）7000番台
            ['name' => 'Fiat',            'name_kana' => 'フィアット',           'display_name' => 'フィアット',       'code' => 'FIAT01',           'url' => null, 'description' => null, 'country_code' => 'IT', 'sort_order' => 7000, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'AlfaRomeo',       'name_kana' => 'アルファロメオ',       'display_name' => 'アルファロメオ',   'code' => 'ALFAROMEO01',      'url' => null, 'description' => null, 'country_code' => 'IT', 'sort_order' => 7010, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Ferrari',         'name_kana' => 'フェラーリ',           'display_name' => 'フェラーリ',       'code' => 'FERRARI01',        'url' => null, 'description' => null, 'country_code' => 'IT', 'sort_order' => 7020, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Lamborghini',     'name_kana' => 'ランボルギーニ',       'display_name' => 'ランボルギーニ',   'code' => 'LAMBORGHINI01',    'url' => null, 'description' => null, 'country_code' => 'IT', 'sort_order' => 7030, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Maserati',        'name_kana' => 'マセラティ',           'display_name' => 'マセラティ',       'code' => 'MASERATI01',       'url' => null, 'description' => null, 'country_code' => 'IT', 'sort_order' => 7040, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Lancia',          'name_kana' => 'ランチア',             'display_name' => 'ランチア',         'code' => 'LANCIA01',         'url' => null, 'description' => null, 'country_code' => 'IT', 'sort_order' => 7050, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Bertone',         'name_kana' => 'ベルトーネ',           'display_name' => 'ベルトーネ',       'code' => 'BERTONE01',        'url' => null, 'description' => null, 'country_code' => 'IT', 'sort_order' => 7060, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Autobianchi',     'name_kana' => 'アウトビアンキ',       'display_name' => 'アウトビアンキ',   'code' => 'AUTOBIANCHI01',    'url' => null, 'description' => null, 'country_code' => 'IT', 'sort_order' => 7070, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Abarth',          'name_kana' => 'アバルト',             'display_name' => 'アバルト',         'code' => 'ABARTH01',         'url' => null, 'description' => null, 'country_code' => 'IT', 'sort_order' => 7080, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Innocenti',       'name_kana' => 'イノチェンティ',       'display_name' => 'イノチェンティ',   'code' => 'INNOCENTI01',      'url' => null, 'description' => null, 'country_code' => 'IT', 'sort_order' => 7090, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'DeTomaso',        'name_kana' => 'デトマソ',             'display_name' => 'デトマソ',         'code' => 'DETOMASO01',       'url' => null, 'description' => null, 'country_code' => 'IT', 'sort_order' => 7100, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],

            // その他の国
            ['name' => 'KTM',             'name_kana' => 'ケーティーエム',       'display_name' => 'KTM',              'code' => 'KTM01',            'url' => null, 'description' => null, 'country_code' => 'AT', 'sort_order' => 7500, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'SEAT',            'name_kana' => 'シート',               'display_name' => 'SEAT',             'code' => 'SEAT01',           'url' => null, 'description' => null, 'country_code' => 'ES', 'sort_order' => 7600, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Adria',           'name_kana' => 'アドリア',             'display_name' => 'アドリア',         'code' => 'ADRIA01',          'url' => null, 'description' => null, 'country_code' => 'SI', 'sort_order' => 7700, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Lada',            'name_kana' => 'ラーダ',               'display_name' => 'ラーダ',           'code' => 'LADA01',           'url' => null, 'description' => null, 'country_code' => 'RU', 'sort_order' => 7800, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'BYD',             'name_kana' => 'ビーワイディー',       'display_name' => 'BYD',              'code' => 'BYD01',            'url' => null, 'description' => null, 'country_code' => 'CN', 'sort_order' => 7900, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Hyundai',         'name_kana' => 'ヒョンデ',             'display_name' => 'ヒュンダイ',       'code' => 'HYUNDAI01',        'url' => null, 'description' => null, 'country_code' => 'KR', 'sort_order' => 8000, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Kia',             'name_kana' => '起亜',                 'display_name' => 'キア',             'code' => 'KIA01',            'url' => null, 'description' => null, 'country_code' => 'KR', 'sort_order' => 8010, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'TD',              'name_kana' => 'ティーディー',         'display_name' => 'TD',               'code' => 'TD01',             'url' => null, 'description' => null, 'country_code' => 'MY', 'sort_order' => 8100, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => 'Barkin',          'name_kana' => 'バーキン',             'display_name' => 'バーキン',         'code' => 'BARKIN01',         'url' => null, 'description' => null, 'country_code' => 'ZA', 'sort_order' => 8200, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
            ['name' => '輸入車その他',    'name_kana' => 'ユウニュウシャソノタ', 'display_name' => '輸入車その他',     'code' => 'IMPORTETC01',      'url' => null, 'description' => null, 'country_code' => 'XX', 'sort_order' => 9999, 'is_active' => 1, 'created_at' => $now, 'updated_at' => $now, 'deleted_at' => null],
        ]);
    }
}